# numpy
* numpy 는 배열을 이용한 연산처리시 유용한 라이브러리이다.

In [1]:
!pip3 show numpy

Name: numpy
Version: 1.13.3
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: NumPy Developers
Author-email: numpy-discussion@python.org
License: BSD
Location: /anaconda3/lib/python3.6/site-packages
Requires: 
Required-by: tables, seaborn, PyWavelets, patsy, pandas, odo, numexpr, numba, matplotlib, h5py, datashape, Bottleneck, bokeh, bkcharts, astropy


In [2]:
import numpy as np
x = np.array([1.0, 2.0, 3.0])
print(x)

[ 1.  2.  3.]


In [3]:
from IPython.display import Image
Image(url= "https://www.geeksforgeeks.org/wp-content/uploads/strassen_new.png")

In [4]:
x = np.array([[1, 2],
       [3, 4]])
print(x)
x.shape

[[1 2]
 [3 4]]


(2, 2)

In [5]:
y = np.array([
        [5, 0],
       [0, 5]]
            )
print(y)


[[5 0]
 [0 5]]


In [6]:
x+y

array([[6, 2],
       [3, 9]])

In [7]:
a=  np.array([[1*5+2*0, 1*0+2*5],
       [3*0+4*0, 3*0+4*5]])
print(a)

[[ 5 10]
 [ 0 20]]


In [8]:
x*y

array([[ 5,  0],
       [ 0, 20]])

https://datascienceschool.net/view-notebook/35099ac4aea146c69cc4b3f50aec736f/